Repository mindvalley/wukong-cli, pull requests merged in 2022-12, with the labels that each got.

#47 Bump version
  Cargo.lock
  Cargo.toml
Labels: size/M

#48 Add CHANGELOG
  .github/img/wukong_help.png
  .github/img/wukong_logo.png
  CHANGELOG.md
  README.md
Labels: size/L

#49 Correct the command to check Wukong CLI version
  README.md
Labels: size/XS

#44 PXP-423: [CLI] Display the build artifact name when listing deployments
  src/commands/deployment/list.rs
  src/graphql/deployment.rs
  src/graphql/query/cd_pipelines.graphql
  src/graphql/schema.json
Labels: enhancement

#46 PXP-426: [CLI] Show which build artifact is the current deployed one when selecting artifact
  src/commands/deployment/execute.rs
  src/graphql/query/cd_pipeline.graphql
  src/graphql/schema.json
Labels: feature, size/L
