Repository mindvalley/wukong-cli, pull requests merged in 2022-11, with the labels that each got.

#33 PXP-412: [Wukong CLI] Remove all the unwrap function
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/auth/mod.rs
  src/commands/completion.rs
  src/commands/config.rs
  src/commands/deployment/execute.rs
  src/commands/deployment/list.rs
  src/commands/deployment/mod.rs
  src/commands/init.rs
  src/commands/login.rs
  src/commands/pipeline/ci_status.rs
  src/commands/pipeline/describe.rs
  src/commands/pipeline/list.rs
  src/commands/pipeline/mod.rs
  src/config.rs
  src/error.rs
  src/graphql/application.rs
  src/graphql/deployment.rs
  src/graphql/pipeline.rs
  src/graphql/query/ci_status.graphql
  src/graphql/query/pipeline.graphql
  src/graphql/schema.json
  src/main.rs
  src/output/error.rs
  src/settings.rs
Labels: enhancement, breaking-change

#34 PXP-418: [Wukong CLI] Asking user to continue to deploy when selecting the same build as current deployed ref.
  src/commands/deployment/execute.rs
  src/error.rs
  src/graphql/changelog.rs
  src/graphql/deployment.rs
  src/graphql/pipeline.rs
Labels: enhancement

#35 PXP-416: [Wukong CLI] Allowing to override the api_url and okta_client_id in the config
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  Cross.toml
  src/app.rs
  src/auth/mod.rs
  src/commands/config.rs
  src/commands/init.rs
  src/config.rs
  src/error.rs
  src/graphql/mod.rs
  src/main.rs
  src/output/error.rs
Labels: enhancement, breaking-change

#37 Update README.md
  README.md
Labels: size/XS

#38 PXP-424: [CLI] Use Short Commit Hash rather than full commit hash
  src/commands/deployment/list.rs
Labels: size/XS

#39 PXP-419: [Wukong CLI] Cursor disappear when terminating the interactive session in the middle.
  Cargo.lock
  Cargo.toml
  src/commands/deployment/execute.rs
  src/commands/init.rs
  src/commands/login.rs
  src/main.rs
  src/output/error.rs
Labels: bug, size/M, lgtm

#40 PXP-417: [Wukong CLI] Don't display selection if it's not available for an application
  src/commands/deployment/execute.rs
  src/error.rs
Labels: enhancement, feature, size/L

#28 PXP-397: [CLI] Support editing the CHANGELOG & Post to Slack
  Cargo.lock
  Cargo.toml
  src/commands/deployment/execute.rs
  src/graphql/deployment.rs
  src/graphql/mod.rs
  src/graphql/mutation/execute_cd_pipeline.graphql
  src/graphql/schema.json
Labels: enhancement, feature, size/XL

#41 PXP-428: [CLI] Display the Trigger User when listing deployments
  src/commands/deployment/list.rs
  src/graphql/query/cd_pipelines.graphql
  src/graphql/schema.json
Labels: feature, size/S

#42 PXP-436: [Wukong CLI] Display message to tell user that there are a deployment with same arguments is running
  src/graphql/deployment.rs
Labels: enhancement, size/M
