Repository mindvalley/wukong-cli, pull requests merged in 2023-12, with the labels that each got.

#180 PXP-633: Better error handling if there is failure on JSON decode
  sdk/src/graphql/mod.rs
Labels: enhancement, size/S

#181 PXP-641: Handle event sender panic
  cli/src/commands/tui/events/mod.rs
Labels: size/XS, bugfix

#182 PXP-638: [CLI] Reached API limits on Google Logging
  cli/src/commands/tui/action.rs
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/handlers/logs.rs
  cli/src/commands/tui/handlers/mod.rs
  cli/src/commands/tui/handlers/time_filter_selection.rs
  cli/src/commands/tui/ui/mod.rs
Labels: size/M, bugfix
