Repository mindvalley/wukong-cli, pull requests merged in 2023-03, with the labels that each got.

#70 PXP-493: [Wukong CLI] Fix the text alignment when listing build artifacts
  src/commands/deployment/execute.rs
Labels: enhancement, size/M

#71 Fix clippy rule
  src/commands/deployment/execute.rs
Labels: size/XS

#69 PXP-474: [CLI] Develop the ability to read annotations in dev config
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/utils/annotations.rs
  src/utils/mod.rs
Labels: feature, size/L

#72 Bumping version to 0.0.6-rc1
  Cargo.lock
  Cargo.toml
  tests/snapshots/completion__wukong_completion_zsh.snap
  tests/snapshots/deployment__wukong_deployment_list_success.snap
  tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/L

#73 PXP-494: [Wukong CLI] Improving the debug log for Okta refresh token flow
  src/auth/mod.rs
Labels: size/XS

#74 fix: remove unused step for macos
  .github/workflows/release.yml
Labels: bug

#75 fix: show refresh token error using debug output
  src/auth/mod.rs
  src/commands/init.rs
  src/commands/mod.rs
Labels: bug, size/XS

#76 PXP-475: [Wukong CLI] Integrate vault client
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/error.rs
  src/lib.rs
  src/services/vault/client.rs
  src/services/vault/mod.rs
Labels: feature, size/XL

#78 PXP-475: [Wukong CLI] Refactor auth logic
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/error.rs
  src/services/vault/mod.rs
Labels: feature, size/L

#77 PXP-489 retry request on query timeout
  src/error.rs
  src/graphql/mod.rs
Labels: size/M
