Repository mindvalley/wukong-cli, pull requests merged in 2023-10, with the labels that each got.

#152 PXP-616: [CLI] Log Entries is not reset after a new namespace or a new version is selected
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/ui/namespace_selection.rs
  cli/src/commands/tui/ui/version_selection.rs
Labels: bug, size/M, bugfix

#151 PXP-597: [CLI] Logs panel: Support search / filter for logs
  Cargo.lock
  cli/Cargo.toml
  cli/src/commands/tui/action.rs
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/mod.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/mod.rs
  cli/src/commands/tui/ui/help.rs
  cli/src/commands/tui/ui/logs.rs
  cli/src/commands/tui/ui/mod.rs
  cli/src/commands/tui/ui/namespace_selection.rs
  cli/src/commands/tui/ui/version_selection.rs
Labels: feature, size/XL

#156 Bump version and update latest dependencies
  Cargo.lock
  cli/Cargo.toml
  cli/tests/snapshots/completion__wukong_completion_fish.snap
  cli/tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/XL

#158 PXP-610: [CLI] Panel Expand
  cli/src/commands/tui/action.rs
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/handlers/build.rs
  cli/src/commands/tui/handlers/deployment.rs
  cli/src/commands/tui/handlers/empty.rs
  cli/src/commands/tui/handlers/log_filter_exclude.rs
  cli/src/commands/tui/handlers/log_filter_include.rs
  cli/src/commands/tui/handlers/log_search.rs
  cli/src/commands/tui/handlers/logs.rs
  cli/src/commands/tui/handlers/mod.rs
  cli/src/commands/tui/handlers/namespace_selection.rs
  cli/src/commands/tui/handlers/version_selection.rs
  cli/src/commands/tui/mod.rs
  cli/src/commands/tui/ui/builds.rs
  cli/src/commands/tui/ui/deployment.rs
  cli/src/commands/tui/ui/logs.rs
  cli/src/commands/tui/ui/mod.rs
  sdk/src/services/gcloud/api/google.api.rs
Labels: feature, size/L

#161 PXP-625: [CLI] Report the Wukong version to telemetry
  telemetry-macro/src/lib.rs
  telemetry/src/lib.rs
Labels: feature, size/S
