Repository mindvalley/wukong-cli, pull requests merged in 2023-07, with the labels that each got.

#116 chore/bump version 1.0.2
  Cargo.lock
  Cargo.toml
  crates/elixir-linter/Cargo.lock
  crates/elixir-linter/Cargo.toml
  tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/XL

#117 PXP-564: [CLI] Polling GraphQLquery for livebook status instead of subscription
  Cargo.lock
  Cargo.toml
  src/commands/application/instances/connect.rs
  src/error.rs
  src/graphql/kubernetes.rs
  src/graphql/mod.rs
  src/graphql/query/livebook_resource.graphql
  src/graphql/schema.json
  src/graphql/subscription/watch_livebook.graphql
Labels: bug, size/XL

#120 Bump version and update dependencies
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/L

#119 PXP-567: [CLI] Crash when entering interactive session too long
  src/commands/application/info.rs
  src/commands/application/instances/connect.rs
  src/commands/application/instances/list.rs
  src/commands/application/logs.rs
  src/commands/config.rs
  src/commands/deployment/execute.rs
  src/commands/deployment/list.rs
  src/commands/deployment/rollback.rs
  src/commands/init.rs
  src/commands/login.rs
  src/commands/mod.rs
  src/commands/pipeline/ci_status.rs
  src/commands/pipeline/describe.rs
  src/commands/pipeline/list.rs
  src/config.rs
  src/error.rs
  src/graphql/application.rs
  src/graphql/changelog.rs
  src/graphql/deployment.rs
  src/graphql/kubernetes.rs
  src/graphql/mod.rs
  src/graphql/pipeline.rs
  src/lib.rs
  src/services/vault/mod.rs
  tests/deployment.rs
  tests/snapshots/deployment__wukong_deployment_list_success.snap
Labels: bug, enhancement, size/XL

#118 PXP-568: [CLI] Make the application instances connect interactive
  completions/bash/wukong.bash
  completions/fish/wukong.fish
  completions/zsh/_wukong
  src/commands/application/instances/connect.rs
  src/commands/application/instances/mod.rs
  src/config.rs
  src/error.rs
  src/output/table.rs
  src/services/gcloud/mod.rs
  src/services/vault/client.rs
  src/telemetry.rs
  tests/snapshots/completion__wukong_completion_bash.snap
  tests/snapshots/completion__wukong_completion_fish.snap
  tests/snapshots/completion__wukong_completion_zsh.snap
Labels: enhancement, size/L

#121 Bump version to 1.1.0
  Cargo.lock
  Cargo.toml
  tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/L

#122 Update README.md
  README.md
Labels: size/XS

#123 Update CHANGELOG
  CHANGELOG.md
Labels: size/S

#124 PXP-571: [CLI] Send telemetry data for new command groups
  crates/wukong_telemetry_macro/src/lib.rs
  src/commands/application/instances/connect.rs
  src/commands/application/logs.rs
  src/commands/dev/config/diff.rs
  src/commands/dev/config/mod.rs
  src/commands/dev/config/pull.rs
  src/commands/dev/config/push.rs
  src/commands/dev/mod.rs
  src/commands/mod.rs
  tests/dev_config.rs
Labels: bug, enhancement, size/M

#125 Bump to version 1.1.1
  Cargo.lock
  Cargo.toml
  tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/M
