Repository mindvalley/wukong-cli, pull requests merged in 2023-06, with the labels that each got.

#102 Bump version to 1.0.0
  Cargo.lock
  Cargo.toml
  tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/L

#105 Fix the reqwest error to stop the retrying during connection check
  src/commands/application/instances/connect.rs
Labels: size/S, bugfix

#106 Update CHANGELOG
  CHANGELOG.md
Labels: size/S

#103 PXP-538: Renew auth token
  src/config.rs
  src/error.rs
  src/services/vault/client.rs
  src/services/vault/mod.rs
  tests/dev_config.rs
Labels: size/L

#107 PXP-547: [CLI] The cli is not working when the refresh token is expired.
  src/auth/mod.rs
  src/commands/init.rs
  src/commands/login.rs
  src/commands/mod.rs
  src/error.rs
Labels: size/L, bugfix

#108 Bump version to 1.0.1
  Cargo.lock
  Cargo.toml
  tests/snapshots/deployment__wukong_deployment_list_success.snap
  tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/L

#109 PXP-549: [API] Google Cloud Oauth2 does not have the resfresh token
  src/services/gcloud/mod.rs
Labels: size/XS, bugfix

#110 chore/update changelog
  CHANGELOG.md
Labels: size/S

#111 chore/add more guides
  README.md
  guides/elixir_working_with_secrets_in_bunker.md
  guides/examples/.wukong.toml.example
  guides/working_with_generic_secrets_in_bunker.md
Labels: size/L

#112 PXP-548: [CLI] Program does not exit on Ctrl-C key press
  src/commands/application/instances/connect.rs
  src/main.rs
Labels: size/S, bugfix

#115 Update elixir_working_with_secrets_in_bunker.md
  guides/elixir_working_with_secrets_in_bunker.md
Labels: size/XS
