Repository mindvalley/wukong-cli, pull requests merged in 2023-11, with the labels that each got.

#166 PXP-631: [CLI] The header layout is broken on big screen
  cli/src/commands/tui/ui/help.rs
Labels: bug, size/S, bugfix

#167 PXP-632: [CLI] Okta tokens did not being updated after refresh
  cli/src/wukong_client.rs
Labels: bugfix

#168 Bump version of the cli
  Cargo.lock
  cli/Cargo.toml
  cli/tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/L

#171 Update CHANGELOG
  CHANGELOG.md
Labels: size/M

#172 Update README to add installation steps
  README.md
  cli/src/commands/mod.rs
  cli/tests/config.rs
  cli/tests/snapshots/config__wukong_config_list_success.snap
Labels: size/S

#170 PXP-617: [CLI] Logs Panel: Support line wrapping
  Cargo.lock
  cli/Cargo.toml
  cli/src/commands/tui/action.rs
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/handlers/logs.rs
  cli/src/commands/tui/ui/logs.rs
Labels: feature, size/L

#175 PXP-639: [CLI] Ctrl-e stopped working on the latest codebase
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/handlers/empty.rs
  cli/src/commands/tui/handlers/logs.rs
  cli/src/commands/tui/handlers/namespace_selection.rs
  cli/src/commands/tui/handlers/time_filter_selection.rs
  cli/src/commands/tui/handlers/version_selection.rs
  cli/src/commands/tui/ui/logs.rs
  cli/src/output/tokenizer.rs
  sdk/src/services/vault/client.rs
Labels: bug, size/L, bugfix

#176 PXP-640: [CLI] Log panel panic when the start index out of bound
  cli/src/commands/tui/handlers/empty.rs
  cli/src/commands/tui/handlers/logs.rs
  cli/src/commands/tui/handlers/namespace_selection.rs
  cli/src/commands/tui/handlers/time_filter_selection.rs
  cli/src/commands/tui/handlers/version_selection.rs
  cli/src/commands/tui/ui/logs.rs
Labels: size/L, bugfix

#173 PXP-634: [CLI] Add welcome before showing TUI panels
  cli/completions/bash/wukong.bash
  cli/completions/fish/wukong.fish
  cli/completions/zsh/_wukong
  cli/src/auth/google_cloud.rs
  cli/src/auth/okta.rs
  cli/src/commands/google/login.rs
  cli/src/commands/google/mod.rs
  cli/src/commands/mod.rs
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/mod.rs
  cli/src/commands/tui/ui/mod.rs
  cli/src/commands/tui/ui/welcome.rs
  cli/src/wukong_client.rs
  cli/tests/snapshots/completion__wukong_completion_bash.snap
  cli/tests/snapshots/completion__wukong_completion_fish.snap
  cli/tests/snapshots/completion__wukong_completion_zsh.snap
  cli/tests/snapshots/wukong__wukong_help_without_config_file.snap
  sdk/src/error.rs
  sdk/src/services/gcloud/mod.rs
Labels: feature, size/XL
