Repository mindvalley/wukong-cli, pull requests merged in 2023-08, with the labels that each got.

#127 PXP-572: Handle blue/green deployment failure on deployment
  src/commands/deployment/execute.rs
Labels: size/M

#130 PXP-577: [CLI] Implement the command
  Cargo.lock
  cli/Cargo.toml
  cli/src/commands/mod.rs
  cli/src/commands/tui.rs
  cli/tests/snapshots/completion__wukong_completion_bash.snap
  cli/tests/snapshots/completion__wukong_completion_fish.snap
  cli/tests/snapshots/completion__wukong_completion_zsh.snap
  cli/tests/snapshots/wukong__wukong_help_without_config_file.snap
Labels: feature, size/L

#131 PXP-578: [CLI] Implement the headers section
  cli/src/commands/tui.rs
Labels: feature, size/L

#132 PXP-584: [CLI] Implement the hotkeys
  cli/src/commands/dev/config/diff.rs
  cli/src/commands/dev/config/utils.rs
  cli/src/commands/tui/hotkey.rs
  cli/src/commands/tui/mod.rs
  cli/tests/deployment.rs
  cli/tests/dev_config.rs
  cli/tests/pipeline.rs
  sdk/crates/elixir-linter/src/rules/no_env_in_dev_config.rs
  sdk/crates/elixir-linter/src/rules/no_env_in_main_config.rs
  sdk/crates/elixir-linter/src/rules/use_import_config_with_file_exists_checking.rs
Labels: feature, size/L

#134 PXP-581: [CLI] Implement the deployment section
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/mod.rs
  cli/src/commands/tui/ui/builds.rs
  cli/src/commands/tui/ui/deployment.rs
  cli/src/commands/tui/ui/namespace_selection.rs
Labels: enhancement, feature, size/L

#133 PXP-580: [CLI] Implement the build artifact section
  cli/src/commands/tui/action.rs
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/key.rs
  cli/src/commands/tui/events/mod.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/hotkey.rs
  cli/src/commands/tui/mod.rs
  cli/src/commands/tui/ui/application.rs
  cli/src/commands/tui/ui/builds.rs
  cli/src/commands/tui/ui/deployment.rs
  cli/src/commands/tui/ui/help.rs
  cli/src/commands/tui/ui/logs.rs
  cli/src/commands/tui/ui/mod.rs
  cli/src/commands/tui/ui/namespace_selection.rs
  cli/src/wukong_client.rs
Labels: enhancement, feature, size/XXL

#137 PXP-579: [CLI] Implement the logs section
  Cargo.lock
  cli/Cargo.toml
  cli/src/commands/application/logs.rs
  cli/src/commands/application/mod.rs
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/mod.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/mod.rs
  cli/src/commands/tui/ui/builds.rs
  cli/src/commands/tui/ui/deployment.rs
  cli/src/commands/tui/ui/logs.rs
  cli/src/commands/tui/ui/namespace_selection.rs
  cli/src/wukong_client.rs
  sdk/src/graphql/schema.json
Labels: enhancement, feature, size/XL
