Repository mindvalley/wukong-cli, pull requests merged in 2023-09, with the labels that each got.

#140 PXP-604: handle permission error for the TUI
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/ui/logs.rs
  cli/src/commands/tui/ui/namespace_selection.rs
  sdk/src/error.rs
  sdk/src/services/gcloud/mod.rs
Labels: bug, size/M

#142 fix: fix errors from the latest dependencies
  cli/src/commands/pipeline/mod.rs
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/ui/deployment.rs
  cli/src/commands/tui/ui/logs.rs
  cli/src/output/table.rs
Labels: bug, size/S, bugfix

#141 Bump version and update to latest dependencies
  Cargo.lock
  cli/Cargo.toml
  cli/src/commands/pipeline/mod.rs
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/ui/deployment.rs
  cli/src/commands/tui/ui/logs.rs
  cli/src/output/table.rs
  cli/tests/snapshots/completion__wukong_completion_bash.snap
  cli/tests/snapshots/wukong__wukong_version_without_config_file.snap
  sdk/Cargo.toml
Labels: size/XL

#143 Update CHANGELOG
  CHANGELOG.md
Labels: size/M

#145 PXP-596: Optimize the logs rendering on tui
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/mod.rs
  cli/src/commands/tui/ui/logs.rs
Labels: size/L

#147 PXP-613: Update API calls order
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/mod.rs
  cli/src/commands/tui/ui/application.rs
  cli/src/commands/tui/ui/deployment.rs
  cli/src/commands/tui/ui/namespace_selection.rs
  cli/src/commands/tui/ui/version_selection.rs
Labels: size/XL, bugfix

#149 PXP-611: add error logs filter on tui
  cli/src/commands/application/logs.rs
  cli/src/commands/tui/action.rs
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/ui/help.rs
  cli/src/commands/tui/ui/logs.rs
Labels: feature, size/M

#148 PXP-598: Add log tailing hotkey
  cli/src/commands/tui/action.rs
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/ui/help.rs
  cli/src/commands/tui/ui/logs.rs
Labels: feature, size/L
