Repository mindvalley/wukong-cli, pull requests merged in 2023-02, with the labels that each got.

#57 PXP-463: [CLI] Implement the rollback command
  completions/bash/wukong.bash
  completions/fish/wukong.fish
  completions/zsh/_wukong
  src/commands/deployment/execute.rs
  src/commands/deployment/mod.rs
  src/commands/deployment/rollback.rs
  src/graphql/changelog.rs
  src/graphql/deployment.rs
  src/graphql/mod.rs
  src/graphql/mutation/execute_cd_pipeline.graphql
  src/graphql/query/cd_pipeline.graphql
  src/graphql/query/cd_pipeline_for_rollback.graphql
  src/graphql/query/changelogs.graphql
  src/graphql/schema.json
Labels: size/XL

#62 PXP-467: [CLI] Generating a default changelog for the rollback operation (re-open)
  src/commands/deployment/rollback.rs
Labels: enhancement, size/S

#63 PXP-468: [CLI] Use the new field to determine what is the current deployed artifact
  src/commands/deployment/execute.rs
  src/graphql/query/cd_pipeline.graphql
  src/graphql/schema.json
Labels: size/S

#64 Bump version to v0.0.5-beta1
  Cargo.lock
  Cargo.toml
  tests/snapshots/application__wukong_application_help.snap
  tests/snapshots/completion__wukong_completion_bash.snap
  tests/snapshots/completion__wukong_completion_fish.snap
  tests/snapshots/completion__wukong_completion_help.snap
  tests/snapshots/completion__wukong_completion_zsh.snap
  tests/snapshots/config__wukong_config_get_should_failed_with_non_supported_field.snap
  tests/snapshots/config__wukong_config_help.snap
  tests/snapshots/config__wukong_config_set_should_failed_with_non_supported_field.snap
  tests/snapshots/deployment__wukong_deployment_help.snap
  tests/snapshots/pipeline__wukong_pipeline_help.snap
  tests/snapshots/wukong__wukong_help_without_config_file.snap
  tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/XL

#65 PXP-481: [Wukong CLI] Telemetry panic when the `~/.config/wukong` path is not exists
  src/commands/config.rs
  src/telemetry.rs
Labels: size/L

#66 Bump version to v0.0.5-beta2
  Cargo.lock
  Cargo.toml
  tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/S

#67 Update CHANGELOG and README
  CHANGELOG.md
  README.md
Labels: size/M
