Repository mindvalley/wukong-cli, pull requests merged in 2023-04, with the labels that each got.

#80 PXP-476: [CLI] Develop the config synthesizer command
  Cargo.lock
  Cargo.toml
  completions/bash/wukong.bash
  completions/fish/wukong.fish
  completions/zsh/_wukong
  src/commands/dev/config_lint.rs
  src/commands/dev/config_synthesizer.rs
  src/commands/dev/mod.rs
  src/commands/init.rs
  src/commands/mod.rs
  src/config.rs
  src/error.rs
  src/lib.rs
  src/services/vault/client.rs
  src/services/vault/mod.rs
  src/utils/annotations.rs
  tests/dev.rs
  tests/snapshots/completion__wukong_completion_bash.snap
  tests/snapshots/completion__wukong_completion_fish.snap
  tests/snapshots/completion__wukong_completion_zsh.snap
  tests/snapshots/dev__wukong_dev_config_lint_success.snap
  tests/snapshots/dev__wukong_dev_config_synthesizer_success.snap
  tests/snapshots/dev__wukong_dev_help.snap
Labels: feature, size/XXL

#83 Bump version to 0.0.7-rc1
  Cargo.lock
  Cargo.toml
  tests/dev.rs
  tests/snapshots/dev__wukong_dev_config_lint_success.snap
  tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/XL

#84 Update CHANGELOG
  CHANGELOG.md
Labels: size/M

#86 PXP-515: [CLI] Develop the config secrets diff command
  Cargo.lock
  Cargo.toml
  completions/bash/wukong.bash
  completions/fish/wukong.fish
  completions/zsh/_wukong
  src/commands/dev/config/diff.rs
  src/commands/dev/config/mod.rs
  src/commands/dev/config/push.rs
  src/commands/dev/config/utils.rs
  tests/dev_config.rs
  tests/snapshots/completion__wukong_completion_bash.snap
  tests/snapshots/completion__wukong_completion_fish.snap
  tests/snapshots/completion__wukong_completion_zsh.snap
  tests/snapshots/deployment__wukong_deployment_list_success.snap
  tests/snapshots/dev_config__wukong_dev_config_diff_success.snap
  tests/snapshots/dev_config__wukong_dev_config_diff_when_config_not_found.snap
  tests/snapshots/dev_config__wukong_dev_config_diff_when_no_changes_found.snap
  tests/snapshots/dev_config__wukong_dev_config_diff_when_secret_file_not_found.snap
  tests/snapshots/dev_config__wukong_dev_config_diff_when_secret_key_not_found_from_bunker.snap
  tests/snapshots/dev_config__wukong_dev_config_help.snap
Labels: feature, size/XXL

#87 PXP-514: [CLI] Rename 'dev config-synthesizer' to 'dev config pull'
  completions/bash/wukong.bash
  completions/fish/wukong.fish
  completions/zsh/_wukong
  src/commands/dev/config/mod.rs
  src/commands/dev/config/pull.rs
  src/commands/dev/mod.rs
  tests/dev.rs
  tests/dev_config.rs
  tests/snapshots/completion__wukong_completion_bash.snap
  tests/snapshots/completion__wukong_completion_fish.snap
  tests/snapshots/completion__wukong_completion_zsh.snap
  tests/snapshots/dev__wukong_dev_help.snap
  tests/snapshots/dev_config__wukong_dev_config_help.snap
  tests/snapshots/dev_config__wukong_dev_config_pull_success.snap
Labels: enhancement, size/XL

#88 PXP-516: [CLI] Fix multiple annotations support
  src/commands/dev/config/diff.rs
  src/commands/dev/config/push.rs
  src/commands/dev/config/utils.rs
  src/error.rs
  tests/dev_config.rs
  tests/snapshots/dev_config__wukong_dev_config_diff_when_secret_key_not_found_from_bunker.snap
Labels: bug, size/L

#90 PXP-517: [CLI] Rename "dev config-lint" command to "dev config lint"
  completions/bash/wukong.bash
  completions/fish/wukong.fish
  completions/zsh/_wukong
  src/commands/dev/config/lint.rs
  src/commands/dev/config/mod.rs
  src/commands/dev/mod.rs
  tests/dev.rs
  tests/dev_config.rs
  tests/snapshots/completion__wukong_completion_bash.snap
  tests/snapshots/completion__wukong_completion_fish.snap
  tests/snapshots/completion__wukong_completion_zsh.snap
  tests/snapshots/dev__wukong_dev_help.snap
  tests/snapshots/dev_config__wukong_dev_config_help.snap
  tests/snapshots/dev_config__wukong_dev_config_lint_success.snap
Labels: enhancement, size/XL

#92 PXP-519: [CLI] Change the linter rule to accept any path declared in the File.exists/2 function
  crates/elixir-linter/src/rules/use_import_config_with_file_exists_checking.rs
  tests/snapshots/dev__wukong_dev_config_lint_success.snap
  tests/snapshots/dev_config__wukong_dev_config_lint_success.snap
Labels: enhancement, size/M

#93 Bump version before release
  Cargo.lock
  Cargo.toml
  tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/L

#94 Update changelogs
  CHANGELOG.md
Labels: size/S

#95 Add a guide for using the Vault integration feature
  README.md
  guides/elixir_working_with_secrets_in_bunker.md
  guides/img/connect_secret_folder.png
  guides/img/create_secrets.png
Labels: size/L

#96 PXP-501: [CLI] Implement the include & exclude flags
  completions/bash/wukong.bash
  completions/fish/wukong.fish
  completions/zsh/_wukong
  src/commands/application/logs.rs
  src/commands/application/mod.rs
  src/services/gcloud/mod.rs
  tests/snapshots/completion__wukong_completion_bash.snap
  tests/snapshots/completion__wukong_completion_fish.snap
  tests/snapshots/completion__wukong_completion_zsh.snap
Labels: feature, size/L
