Repository mindvalley/wukong-cli, pull requests merged in 2024-02, with the labels that each got.

#192 PXP-644 feat: add application init command
  Cargo.lock
  cli/Cargo.toml
  cli/src/commands/application/config.rs
  cli/src/commands/application/init.rs
  cli/src/commands/application/mod.rs
  cli/src/config.rs
  cli/src/error.rs
  cli/tests/snapshots/application__wukong_application_help.snap
  cli/tests/snapshots/completion__wukong_completion_bash.snap
  cli/tests/snapshots/completion__wukong_completion_fish.snap
  cli/tests/snapshots/completion__wukong_completion_zsh.snap
Labels: feature, size/XL

#193 PXP-664 refactor: replace global init with inquire library
  cli/src/auth/google_cloud.rs
  cli/src/auth/okta.rs
  cli/src/commands/config/get.rs
  cli/src/commands/config/set.rs
  cli/src/commands/google/login.rs
  cli/src/commands/init.rs
  cli/src/commands/login.rs
  cli/src/commands/mod.rs
  cli/src/config.rs
  cli/src/loader.rs
  cli/tests/application.rs
  cli/tests/application_instances.rs
  cli/tests/config.rs
  cli/tests/deployment.rs
  cli/tests/dev_config.rs
  cli/tests/pipeline.rs
  cli/tests/snapshots/config__wukong_config_get_success.snap
  cli/tests/snapshots/config__wukong_config_list_success.snap
  cli/tests/snapshots/config__wukong_config_list_success_without_login.snap
Labels: size/L, refactor

#194 Fix: Apply new clippy changes for for rust version (1.26.0)
  cli/src/commands/application/logs.rs
Labels: size/XS, bugfix

#195 chore(github): update github actions
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: size/S

#197 Fix/handle broken google cloud welcome screen on tui
  cli/src/auth/google_cloud.rs
  cli/src/commands/google/login.rs
  cli/src/commands/init.rs
Labels: size/S, bugfix
