Repository mindvalley/wukong-cli, pull requests merged in 2024-01, with the labels that each got.

#185 PXP-663: [CLI] Depreciate old error handling
  sdk/src/graphql/changelog.rs
  sdk/src/graphql/deployment.rs
  sdk/src/graphql/deployment_github.rs
  sdk/src/graphql/kubernetes.rs
  sdk/src/graphql/mod.rs
  sdk/src/graphql/pipeline.rs
Labels: size/L, bugfix

#184 PXP-662 fix: pipeline status request does not need builds
  cli/src/commands/deployment/execute.rs
  cli/src/wukong_client.rs
  sdk/src/error.rs
  sdk/src/graphql/deployment.rs
  sdk/src/graphql/mod.rs
  sdk/src/graphql/query/cd_pipeline_status.graphql
Labels: size/M

#188 Update upload-artifact action to v4
  .github/workflows/release.yml
Labels: size/XS

#189 Fix a typo in the download action
  .github/workflows/release.yml
Labels: size/XS

#190 Add artifact download path to release workflow
  .github/workflows/release.yml
Labels: size/XS

#183 PXP-638: [CLI] Implement new config
  Cargo.lock
  cli/Cargo.toml
  cli/src/auth/google_cloud.rs
  cli/src/auth/okta.rs
  cli/src/auth/vault.rs
  cli/src/commands/application/logs.rs
  cli/src/commands/google/login.rs
  cli/src/commands/google/mod.rs
  cli/src/commands/init.rs
  cli/src/commands/login.rs
  cli/src/commands/mod.rs
  cli/src/commands/tui/events/network.rs
  cli/src/config.rs
  cli/src/wukong_client.rs
  cli/tests/application.rs
  cli/tests/application_instances.rs
  cli/tests/config.rs
  cli/tests/deployment.rs
  cli/tests/dev_config.rs
  cli/tests/pipeline.rs
  cli/tests/snapshots/config__wukong_config_list_success.snap
  cli/tests/snapshots/config__wukong_config_list_success_without_login.snap
Labels: feature, size/XL

#191 PXP-659 feat: add cloud sql instances and metric clients from google protobuf…
  sdk/build.rs
  sdk/src/services/gcloud/api/google.api.rs
  sdk/src/services/gcloud/api/google.cloud.sql.v1.rs
  sdk/src/services/gcloud/api/google.monitoring.v3.rs
Labels: size/XXL
