Repository mindvalley/wukong-cli, pull requests merged in 2024-03, with the labels that each got.

#199 PXP-672: [CLI] Include .yaml file types in application init workflow list
  cli/src/commands/application/init.rs
Labels: size/XS

#203 PXP-676: [CLI] Skip workflow step on application init if empty
  cli/src/commands/application/init.rs
Labels: size/M, bugfix

#201 PXP-675: [CLI] Make canary flag enabled by default
  cli/src/commands/mod.rs
Labels: size/XS

#198 PXP-670: [CLI] Implement the AppSignal integration to the deployment status command
  cli/completions/bash/wukong.bash
  cli/completions/fish/wukong.fish
  cli/completions/zsh/_wukong
  cli/src/application_config.rs
  cli/src/commands/application/init.rs
  cli/src/commands/application/logs.rs
  cli/src/commands/application/mod.rs
  cli/src/commands/config/get.rs
  cli/src/commands/config/mod.rs
  cli/src/commands/config/set.rs
  cli/src/commands/deployment/mod.rs
  cli/src/commands/deployment/status.rs
  cli/src/commands/dev/config/mod.rs
  cli/src/commands/mod.rs
  cli/src/commands/tui/app.rs
  cli/src/commands/tui/events/network.rs
  cli/src/commands/tui/mod.rs
  cli/src/commands/tui/ui/appsignal.rs
  cli/src/config.rs
  cli/src/error.rs
  cli/src/output/table.rs
  cli/src/output/tokenizer.rs
  cli/src/wukong_client.rs
  cli/tests/application.rs
  cli/tests/application_instances.rs
  cli/tests/config.rs
  cli/tests/deployment.rs
  cli/tests/dev_config.rs
  cli/tests/pipeline.rs
  cli/tests/snapshots/application__wukong_application_help.snap
  cli/tests/snapshots/application__wukong_application_info_should_failed_when_application_config_not_exist.snap
  cli/tests/snapshots/application_instances__wukong_application_instances_help.snap
  cli/tests/snapshots/application_instances__wukong_application_instances_list_should_failed_when_application_config_file_not_exist.snap
  cli/tests/snapshots/completion__wukong_completion_bash.snap
  cli/tests/snapshots/completion__wukong_completion_fish.snap
  cli/tests/snapshots/completion__wukong_completion_help.snap
  cli/tests/snapshots/completion__wukong_completion_zsh.snap
  cli/tests/snapshots/config__wukong_config_get_should_failed_with_non_supported_field.snap
  cli/tests/snapshots/config__wukong_config_get_success.snap
  cli/tests/snapshots/config__wukong_config_help.snap
  cli/tests/snapshots/config__wukong_config_list_success.snap
  cli/tests/snapshots/config__wukong_config_list_success_without_login.snap
  cli/tests/snapshots/config__wukong_config_set_should_failed_with_non_supported_field.snap
  cli/tests/snapshots/config__wukong_config_set_success_with_supported_field.snap
  cli/tests/snapshots/deployment__wukong_deployment_help.snap
  cli/tests/snapshots/deployment__wukong_deployment_list_should_failed_when_application_config_file_not_exist.snap
  cli/tests/snapshots/dev__wukong_dev_help.snap
  cli/tests/snapshots/dev_config__wukong_dev_config_help.snap
  cli/tests/snapshots/pipeline__wukong_pipeline_ci_status_should_failed_when_application_config_not_exist.snap
  cli/tests/snapshots/pipeline__wukong_pipeline_describe_should_failed_when_application_config_not_exist.snap
  cli/tests/snapshots/pipeline__wukong_pipeline_help.snap
  cli/tests/snapshots/pipeline__wukong_pipeline_list_should_failed_when_application_config_not_exist.snap
  cli/tests/snapshots/wukong__wukong_help_without_config_file.snap
  sdk/src/graphql/appsignal.rs
  sdk/src/graphql/mod.rs
  sdk/src/graphql/query/appsignal_deploy_markers.graphql
  sdk/src/graphql/query/appsignal_exception_incidents.graphql
  sdk/src/graphql/schema.json
  sdk/src/services/gcloud/mod.rs
Labels: feature, size/XXL

#208 chore: add telemetry for deployment status command
  cli/src/commands/deployment/status.rs
Labels: size/XS

#209 PXP-685: [CLI] Improve the warning when CloudSQL integration is not enabled
  cli/src/commands/deployment/status.rs
Labels: enhancement, size/M

#210 chore: cleanup dependencies and use workspace dependencies for share …
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/auth/google_cloud.rs
  cli/tests/snapshots/completion__wukong_completion_fish.snap
  cli/tests/snapshots/completion__wukong_completion_zsh.snap
  cli/tests/snapshots/deployment__wukong_deployment_list_success.snap
  sdk/Cargo.lock
  sdk/Cargo.toml
  sdk/src/error.rs
  telemetry/Cargo.toml
Labels: enhancement, size/XXL

#211 Bump version and dependencies
  Cargo.lock
  cli/Cargo.toml
  cli/src/auth/google_cloud.rs
  cli/tests/snapshots/wukong__wukong_version_without_config_file.snap
Labels: size/L

#212 Update documentation about the breaking changes in version 2.1.0.
  README.md
  guides/upgrade_from_2.0.x_to_2.1.0.md
Labels: size/M

#213 Update changelog
  CHANGELOG.md
Labels: size/M
